#!/usr/bin/env python3
"""
Cleanup script for generated image files before git commit
"""

import os
import glob

def cleanup_generated_images():
    """Remove generated test images that can be recreated"""
    
    # Files to delete (generated test outputs)
    files_to_delete = [
        "all_curve_intersections.png",
        "composite_curves.png", 
        "constructive_geometry.png",
        "curve_gallery.png",
        "intersection_analysis.png",
        "intersection_tests.png",
        "multi_segment_intersections.png",
        "overlapping_curves_analysis.png",
        "precise_intersection_test.png"
    ]
    
    # Old failure/debug files to delete
    debug_files_to_delete = [
        "overlapping_segments_failure.txt",
        "remaining_failures_detail.txt", 
        "serialization_failure.txt",
        "serialization_structure_failure.txt",
        "tolerance_handling_failure.txt",
        "trimmed_curve_failure.txt"
    ]
    
    print("🧹 CLEANING UP GENERATED IMAGE FILES")
    print("=" * 50)
    
    deleted_count = 0
    
    for filename in files_to_delete + debug_files_to_delete:
        if os.path.exists(filename):
            try:
                os.remove(filename)
                print(f"  ✅ Deleted: {filename}")
                deleted_count += 1
            except Exception as e:
                print(f"  ❌ Failed to delete {filename}: {e}")
        else:
            print(f"  ⏭️  Not found: {filename}")
    
    print(f"\n📊 SUMMARY:")
    print(f"  Files deleted: {deleted_count}")
    print(f"  Files kept: UML diagrams, animations, and core documentation")
    
    # Show what's left
    remaining_images = glob.glob("*.png") + glob.glob("*.gif")
    if remaining_images:
        print(f"\n📁 REMAINING IMAGE FILES:")
        for img in sorted(remaining_images):
            print(f"  📄 {img}")
    
    print(f"\n✅ Cleanup complete!")
    print(f"💡 Note: Test images can be regenerated by running the test scripts")

if __name__ == "__main__":
    cleanup_generated_images()